### ISSUE TITLE
How to get the label of Standford Action dataset based on mood/Location criterion?

### ISSUE THREAD

**Issue by rain305f** [sehyunkwon/ICTC#2]
Thanks for fancy work! According to the guidance given in readme.md, I cannot find the labels of Standford Action dataset based on mood/Location criterion. Thank for authors again.

**Comment by sehyunkwon** [comment]
Hi! Thank you for your attention. You can download it on the Google Drive link -> [Link](https://drive.google.com/drive/folders/1dgy_t48xtmRt9ovsiAVHYAWWMVzHghZJ?usp=drive_link)

**Comment by rain305f** [comment]
Thanks！
