### ISSUE TITLE
What's the configuration of the hardware involved in the experiment?

### ISSUE THREAD

**Issue by tanyz0208** [sehyunkwon/ICTC#3]
As for step 1, I use 5 RTX4090. But it still pops out the "cuda out of memory" error. Could you specify the configuration of of your hardware?

**Comment by jadenpark0** [comment]
Hi, thank you for your interest in our work. 

Throughout, we have used a single A100 GPU with 40GB memory for a single thread of step 1. The LLaVA model should use ~30GB of gpu memory.
